name: Automatic publish of npm package

on:
  release:
    types: [published]

run-name: Publishing ${{ github.event.release.tag_name }} to npmjs

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.release.tag_name }}

      - name: Setup Node and install from cache if exists
        uses: ./.github/actions/setup-node

      - name: Run tests for source
        run: npm run test:source

  publish-package:
    needs: test-module
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.release.tag_name }}

      - name: Setup Node and install from cache if exists
        uses: ./.github/actions/setup-node

      - name: Build the package
        run: npm run build

      - name: Run tests for built package
        run: npm run test:build

      - name: Clean package.json for publishing
        run: |
          npm pkg delete scripts
          npm pkg delete devDependencies
          npm pkg delete engines
          npm pkg delete engineStrict

      - name: Publish the package to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GA_NPM_PUBLISH_TOKEN }}

      - name: Setup Node for GHP and install from cache if exists
        uses: ./.github/actions/setup-node
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish the package to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/ --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
