name: Manual publish of npm package
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version tag to test"
        required: true

run-name: Publish version ${{ github.event.inputs.version }} to npmjs

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.inputs.version }}

      - name: Setup Node and install from cache if exists
        uses: ./.github/actions/setup-node

      - name: Run tests for source
        run: npm run test:source

  publish-package:
    needs: test-module
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.inputs.version }}

      - name: Setup Node and install from cache if exists
        uses: ./.github/actions/setup-node

      - name: Build the package
        run: npm run build

      - name: Run tests for built package
        run: npm run test:build

      - name: Publish the package to npm
        run: |
          npm pkg delete scripts
          npm pkg delete devDependencies
          npm pkg delete engines
          npm pkg delete engineStrict
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GA_NPM_PUBLISH_TOKEN }}
