name: Manual publish of npm package
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version tag to test"
        required: true

run-name: Publish version ${{ github.event.inputs.version }} to npmjs

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.inputs.version }}
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      #     registry-url: "https://registry.npmjs.org"
      # - name: Cache npm dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Checkout the code and setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node--version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  publish-package:
    needs: test-module
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ github.event.inputs.version }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Read npm dependencies from cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GA_NPM_PUBLISH_TOKEN }}
