name: Publish package to npmjs
run-name: Publish package
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
jobs:
  on-success:
    name: Publish package to npm
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: tag

      - name: Get tag from artifact
        id: get-tag
        run: |
          tag=$(cat tag.txt)
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/tags/${{ steps.get-tag.outputs.tag }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
