name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version tag to test"
        required: true

run-name: Testing version ${{ github.event.inputs.version }}

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Test
        run: echo "shit"
      - name: Pass chosen version to artifacts
        run: echo "${{ github.event.inputs.version }}" > tag.txt
      - name: Upload tag.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tag
          path: tag.txt
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
